#!/usr/bin/env python
import os
import uuid
import argparse
import ROOT

from triggers import L1_ITEMS, HLT_ITEMS, list_to_vector


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('step', type=str, choices=['l1', 'hlt'], help='Choose l1 or hlt')
    parser.add_argument('sample', type=str, choices=['Z', 'EB'], help='Choose Z or EB')
    parser.add_argument(
        '--path', type=str, 
        default='/afs/cern.ch/user/q/qbuat/work/public/mc15_13TeV/test/', 
        help='default = %(default)s')
    parser.add_argument('--run-dir', type=str, default=None, help='default = %(default)s')
    parser.add_argument('--l1-trig', type=str, default=None, help='default = %(default)s')
    parser.add_argument('--hlt-trig', type=str, default='HLT_tau25_perf_tracktwo', help='default = %(default)s')
    parser.add_argument('--hlt-ref-trig', type=str, default='HLT_tau25_idperf_tracktwo', help='default = %(default)s')
    parser.add_argument('--verbose', default=False, action='store_true', help='default = %(default)s')
    parser.add_argument('--num-events', default=-1, type=int, help='default = %(default)s')
    args = parser.parse_args()

    ROOT.gROOT.Macro('$ROOTCOREDIR/scripts/load_packages.C')
    if not ROOT.xAOD.Init().isSuccess():
        raise RuntimeError

    # Get SampleHandler from EOS
    from eos import get_sample, SAMPLES
    sample = get_sample(SAMPLES[args.sample])
    sample.printContent()
    sample.setMetaString ("nc_tree", "CollectionTree")
    
    # sh = ROOT.SH.SampleHandler()
    # path = ROOT.gSystem.ExpandPathName(args.path)
    # ROOT.SH.ScanDir().sampleDepth(0).scan(sh, path)
    # sh.setMetaString ("nc_tree", "CollectionTree")
    # sh.printContent()
    
    if args.l1_trig != None:
        L1_TRIGGERS = [args.l1_trig]
    else:
        L1_TRIGGERS = L1_ITEMS

    if args.hlt_trig != None:
        HLT_TRIGGERS = [args.hlt_trig]
    else:
        HLT_TRIGGER = HLT_ITEMS

    if args.step == 'l1':
        alg = ROOT.L1EmulationLoop()
        alg.l1_chains = list_to_vector(L1_TRIGGERS)
    else:
        alg = ROOT.HLTEmulationLoop()
        alg.l1_chains = list_to_vector(L1_TRIGGERS)
        alg.reference_chain = args.hlt_ref_trig
        alg.chains_to_test = list_to_vector(HLT_TRIGGERS)

    alg.SetName('EmulationLoop')
    if args.verbose:
        # See atlas/Control/AthToolSupport/AsgTools/AsgTools/MsgLevel.h
        alg.setMsgLevel(1) # VERBOSE
    else:
        alg.setMsgLevel(3) # INFO

    # Setup the EventLoop Job
    job = ROOT.EL.Job()
    job.sampleHandler(sample)
    job.algsAdd(alg)

    if args.num_events > 0:
      job.options().setDouble(ROOT.EL.Job.optMaxEvents, args.num_events)

    # define the run dir
    if args.run_dir == None:
        run_dir = 'run_' + uuid.uuid4().hex
    else:
        run_dir = args.run_dir
        
    # run, run, run!
    driver = ROOT.EL.DirectDriver()
    driver.submit(job, run_dir)

